const Map<String, String> localization = {
  "languageEnglish": "English",
  "languageChinese": "Chinese",
  "title": "Ivy Goal",
  "signIn": "Sign In",
  "signUp": "Sign Up",
  "login": "Login",
  "logInWithWeChat": "Log in with WeChat",
  "logInWithEmail": "Log in with Email",
  "forgotPassword": "Forgot password?",
  "createAccount": "Create account",
  "somethingWentWrong": "Something went wrong",
  "score": "Score",
  "level": "Level",
  "logOut": "Log out",
  "email": "Email",
  "password": "Password",
  "enterName": "Enter your name",
  "name": "Name",
  "enterCity": "Enter your city",
  "city": "City",
  "enterVoivod": "Enter your voivodeship",
  "voivodeship": "Voivodeship",
  "enterAge": "Enter your age",
  "age" : "Age",
  "enterGender": "Enter your gender",
  "gender": "Gender",
  "validEmail": "Enter a valid email",
  "minChar": "Enter min 6 characters",
  "notUser": "Still not a user?",
  "alreadyUser": "Already a user?",
  "createAnAccount": "Create an account!",
  "logInIn": "Log in",
  "back": "Go back",
  "or": "or",
  "testCompleted": "Test Completed!",
  "retake": "Retake Test",
  "nextLevel": "Next Level",
  "submit": "Submit Answer",
  "youtScore": "Your score is",
  "estimatedGrade": "Estimated Grade Level:",
  "estimatedVocabulary": "Estimated Vocabulary Size:",
  "recommendedCourse": "Recommended Course:",
  "potential": "Potential Challenge:",
  "emailAddressUsed": "The email address is already in use by another account.",
  "passwordInvalid": "The password is invalid or the user does not have a password.",
  "suppliedAuth": "The supplied auth credential is malformed or has expired.",
  "basicV": "Basic Vocabulary",
  "intermediateV": "Intermediate Vocabulary",
  "advancedV": "Advanced Vocabulary",
  "app_name": "IvyGoal",
  "potenN": "None",
  "potenAdv": "Advanced Topics",
  "intermediateT": "Intermediate Topics",
  "emailFormated": "The email address is badly formatted.",
  "accountExists": "An account already exists with the same email address but different sign-in credentials. Sign in using a provider associated with this email address."
};